import PDFDocument from "pdfkit";
import { Transaction } from "../../models/transactionModel.js";

const getTransactionReceiptHandler = async (req, res) => {
  try {
    const transaction = await Transaction.findOne({
      _id: req.params.id,
     
    }).populate("user", "username");
    console.log(req.params.id)
    console.log(req.user.id)
    console.log(transaction)
    if (!transaction) {
      return res.status(404).json({
        message: "Transaction not found",
      });
    }

    // =========================
    // SAFE VALUES
    // =========================

    const quantity = Number(transaction.quantity) || 0;

    const subtotal = Number(transaction.subtotal) || 0;

    // New transactions have unitPrice.
    // Old transactions may not, so calculate it as fallback.
    const unitPrice =
      transaction.unitPrice !== undefined &&
      transaction.unitPrice !== null
        ? Number(transaction.unitPrice)
        : quantity > 0
        ? subtotal / quantity
        : 0;

    const transactionType = transaction.trxType
      ? transaction.trxType.toUpperCase()
      : "UNKNOWN";

    // =========================
    // CREATE PDF
    // =========================

    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
    });

    res.setHeader(
      "Content-Type",
      "application/pdf"
    );

    res.setHeader(
      "Content-Disposition",
      `attachment; filename="receipt-${transaction._id}.pdf"`
    );

    doc.pipe(res);

    // =========================
    // HEADER
    // =========================

    doc
      .fontSize(24)
      .font("Helvetica-Bold")
      .text("INVENTORY RECEIPT", {
        align: "center",
      });

    doc.moveDown();

    doc
      .fontSize(12)
      .font("Helvetica")
      .text(
        `Transaction ID: ${transaction._id}`
      );

    doc.text(
      `Date: ${new Date(
        transaction.createdAt
      ).toLocaleString()}`
    );

    doc.moveDown();

    // =========================
    // TRANSACTION TYPE
    // =========================

    doc
      .fontSize(15)
      .font("Helvetica-Bold")
      .text(
        `Transaction Type: ${transactionType}`
      );

    doc.moveDown();

    // =========================
    // PRODUCT DETAILS
    // =========================

    doc
      .fontSize(14)
      .font("Helvetica-Bold")
      .text("Product Details");

    doc.moveDown(0.5);

    doc
      .fontSize(12)
      .font("Helvetica")
      .text(
        `Product: ${
          transaction.productname || "N/A"
        }`
      );

    doc.text(
      `Quantity: ${quantity}`
    );

    doc.text(
      `Unit Price: BDT ${unitPrice.toFixed(2)}`
    );

    doc.text(
      `Subtotal: BDT ${subtotal.toFixed(2)}`
    );

    doc.text(
      `Warehouse: ${
        transaction.warehouseName || "N/A"
      }`
    );

    // =========================
    // SUPPLIER
    // =========================

    if (transaction.trxType === "purchase") {
      doc.moveDown();

      doc
        .fontSize(14)
        .font("Helvetica-Bold")
        .text("Supplier");

      doc.moveDown(0.5);

      doc
        .fontSize(12)
        .font("Helvetica")
        .text(
          transaction.supplier || "N/A"
        );
    }

    // =========================
    // USER
    // =========================

    doc.moveDown();

    doc
      .fontSize(14)
      .font("Helvetica-Bold")
      .text("Processed By");

    doc.moveDown(0.5);

    doc
      .fontSize(12)
      .font("Helvetica")
      .text(
        transaction.user?.username || "N/A"
      );

    // =========================
    // TOTAL
    // =========================

    doc.moveDown(2);

    doc
      .fontSize(18)
      .font("Helvetica-Bold")
      .text(
        `TOTAL: BDT ${subtotal.toFixed(2)}`,
        {
          align: "right",
        }
      );

    doc.moveDown(3);

    doc
      .fontSize(10)
      .font("Helvetica")
      .text(
        "Generated by Inventory Management System",
        {
          align: "center",
        }
      );

    doc.end();

  } catch (error) {
    console.error(
      "Receipt generation error:",
      error
    );

    // Don't try to send another response
    // if PDF streaming has already started.
    if (!res.headersSent) {
      return res.status(500).json({
        message: "Failed to generate receipt",
      });
    }
  }
};

export default getTransactionReceiptHandler;